---
  - name: Copy files
    become: true
    copy:
      src: /artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
  
  - name: Unarchive
    become: true
    shell: |
      cd /home/ubuntu
      tar -xvf artifact.tar.gz -C .
      rm artifact.tar.gz
  
  - name: "run server"
    become: true
    shell: |
      cd /home/ubuntu
      npm install
      pm2 stop default
      pm2 start npm -- start